# Caesar cipher
# This is one of the simplest techniques to encrypt text,
# which consists of substituting each letter of the plain text with the letter
# found at a fixed number of positions down the alphabet.
# For example, with a shift of 5, a would be replaced by f, b by g and so on.

# alphabet = 'abcdefghijklmnopqrstuvwxyz'
# shift = 5
# shifted_alphabet = alphabet[shift:] + alphabet[:shift]  ## here i am using the slice method to take out the alphabets form 5th index and then adding that in last
## The str.maketrans() method takes two strings of equal length and returns a translation table that maps each character of the first string with the corresponding character of the second string.
## Each character in the translation table is stored as a Unicode ordinal, a number that uniquely identifies the character.
# translation_table = str.maketrans(alphabet,shifted_alphabet)
## The translate() method takes as argument the translation table generated by str.maketrans().
## It is called on a string and returns a copy of the original string where the characters have been replaced based on the translation table:
# text = "hello world"
# encrypted_text = text.translate(translation_table)
# print(encrypted_text)

#to reuse this code creating a function
def caesar(text, shift, encrypt = True):

    if not isinstance(shift, int):
        return 'Shift must be an integer value.'

    if shift < 1 or shift > 25:
        return 'Shift must be an integer between 1 and 25.'
    alphabet = 'abcdefghijklmnopqrstuvwxyz'
    if not encrypt:
        shift = - shift
    shifted_alphabet = alphabet[shift:] + alphabet[:shift]
    #although the message is encrypted, the uppercase characters have been left untouched.
    # This happens because the translation table does not include uppercase letters.
    # So Update the str.maketrans() call by concatenating to each argument the uppercase version of the argument itself.
    translation_table = str.maketrans(alphabet + alphabet.upper(), shifted_alphabet + shifted_alphabet.upper())
    encrypted_text = text.translate(translation_table)
    return encrypted_text
def encrypt(text , shift):
    return caesar(text,shift)
def decrypt(text, shift):
    return caesar(text,shift,False)

encrypted_text = 'Zl anzr vf Qunanawnln  Arggvxrer Enwh.'
decrypted_text = decrypt(encrypted_text, 13)
print(decrypted_text)